POST http://localhost:3001/1.0/register/
content-type: application/json

{
    "rut": "18109416-8",
    "name": "Giovannig",
    "lastname": "Barra",
    "age": 21,
    "direction": "Pasaje las palmeras",
    "email": "gio.barra@duocuc.cl",
    "password": "12345678",
    "esp": ""
}

###

POST http://localhost:3001/1.0/login/
content-type: application/json

{
    "email": "lu.saezd@duocuc.cl",
    "password": "261002"
}

###

GET http://localhost:3003/1.0/productos/categorias/1


###

GET http://localhost:3003/1.0/productos/marca/2


###
POST http://localhost:3003/1.0/productos/6
content-type: application/json

{
    "id_sucursal": 2
}

###
POST http://localhost:3002/1.0/pedidos
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uSUQiOiI2ODhkNmEwOC1jOTU5LTQ3N2UtOGMwNS1mMmM2YThmNGU2MTAiLCJ1c2VyIjp7ImVtYWlsIjoibHUuc2FlemRAZHVvY3VjLmNsIn0sInJvbGUiOiJDbGllbnRlIiwiYWRtaW4iOmZhbHNlLCJleHAiOm51bGwsImlhdCI6MTcxNjE0MDU2NH0.-INNFWyhNnMDtbMhCnHMzMcp00dmQyGFnv79CVx9fBo"
content-type: application/json

{
    "cliente": {
        "rut": "20913053-K"
    },
    "detalles": [
        {
            "cantidad": 1,
            "product": {
                "id_producto": 1
            },
            "sucursal": 1
        },
        {
            "cantidad": 1,
            "product": {
                "id_producto": 2
            },
            "sucursal": 1
        }
    ]
}


###

GET http://localhost:3003/1.0/productos/1/usd

###
PUT http://localhost:3003/1.0/productos/1
content-type: application/json

{
    "descuento": 40,
    "categoria": 1,
    "estado": 3
}